spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: https://google.com
        predicates:
        - Method=GET,POST
      uris: #Custom config block
        upper: https://yandex.ru


